mail:
    from: "alcanzartesting@gmail.com"
    to: "gttudor@gmail.com, rishabhsinghchauhanpsit@gmail.com"
    cc: "rishabhsinghchauhanpsit@gmail.com"
# see https://github.com/andris9/nodemailer-smtp-transport#usage
smtp:
    host: "smtp.sendgrid.net"
    port: 587
    auth:
        user: 'madhulas'
        pass: 'thirdeye123'
# Events list:
# - restart
# - delete
# - stop
# - restart overlimit
# - exit
# - start
# - online
events:
    - restart
    - exit
template: './template.md'
# this is the process subject if there is only one event to be mailed
subject: '<%= process.name %> errored (<%= process.NODE_ENV %>)'
# if multiple events are going to be mailed, use a global subject:
multiple_subject: 'Error on <%= hostname %>'
#wait for 5 seconds after each event before sending an email - avoid spam when a lot of events happened
polling: 2500
#attach your process logs to the email
attach_logs: true
